language: node
node_js:
  "4"
before_script:
  - npm install
script:
  - ./node_modules/.bin/gulp build
  - ./node_modules/.bin/gulp test
branches:
  only:
    - master
notifications:
  email:
    - cjmungall@lbl.gov
